version: '3.7'
services:
  nodejs-backend:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: nodejs-backend
    volumes:
       - ./nodejs:/app/nodejs
       - /app/nodejs/node_modules
  vuejs-frontend:
    build:
      context: ./vuejs
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: vuejs-frontend
    volumes:
       - ./vuejs:/app/vuejs
       - /app/vuejs/node_modules