version: '3.7'
services:
  nodejs-backend:
    image: gcr.io/line-p2plid/vue-js-onboarding-nodejs
    build:
      context: ./nodejs
    ports:
      - "3080:3080"
    container_name: nodejs-backend
    volumes:
       - ./nodejs:/app/nodejs
       - /app/nodejs/node_modules
  vuejs-frontend:
    image: gcr.io/line-p2plid/vue-js-onboarding-vuejs
    build:
      context: ./vuejs
    ports:
      - "80:8080"
    container_name: vuejs-frontend
    volumes:
       - ./vuejs:/app/vuejs
       - /app/vuejs/node_modules
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer