apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-backend
  name: nodejs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs-backend
    spec:
      containers:
      - image: gcr.io/line-p2plid/vue-js-onboarding-nodejs
        imagePullPolicy: ""
        name: nodejs-backend
        ports:
        - containerPort: 3080
        resources: {}
        volumeMounts:
        - mountPath: /app/nodejs
          name: nodejs-backend-claim0
        - mountPath: /app/nodejs/node_modules
          name: nodejs-backend-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nodejs-backend-claim0
        persistentVolumeClaim:
          claimName: nodejs-backend-claim0
      - name: nodejs-backend-claim1
        persistentVolumeClaim:
          claimName: nodejs-backend-claim1
status: {}
