apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vuejs-frontend
  name: vuejs-frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: vuejs-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
