apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vuejs-frontend
  name: vuejs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vuejs-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: vuejs-frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: gcr.io/line-p2plid/vue-js-onboarding-vuejs
        imagePullPolicy: ""
        name: vuejs-frontend
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/vuejs
          name: vuejs-frontend-claim0
        - mountPath: /app/vuejs/node_modules
          name: vuejs-frontend-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: vuejs-frontend-claim0
        persistentVolumeClaim:
          claimName: vuejs-frontend-claim0
      - name: vuejs-frontend-claim1
        persistentVolumeClaim:
          claimName: vuejs-frontend-claim1
status: {}
